config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SerchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<footer>
    &copy; Honoka
</footer>

templates/partials/nav.html
<a class="font-semibold text-2xl" href="{% url 'core:home' %}">HONOKA</a>
<ul class="flex w-1/6 justify-end">
    <li class="ml-5">
        <a href="{% url 'rooms:search' %}">
            <i class="fas fa-search fa-lg"></i>
        </a>
    </li>
    {% if user.is_authenticated %}
        <li class="ml-5"><a href="{% url 'rooms:create' %}"><i class="fas fa-cloud-upload-alt fa-lg"></i></a></li>
        <li class="ml-5"><a href="{{user.get_absolute_url}}"><i class="fas fa-user-circle fa-lg"></i></a></li>
        <li class="ml-5"><a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt fa-lg"></i></a></li>
    {% else %}
        <li class="ml-5"><a href="{% url 'users:login' %}"><i class="fas fa-sign-in-alt fa-lg"></i></a></li>
        <li class="ml-5"><a href="{% url 'users:signup' %}"><i class="fas fa-user-plus fa-lg"></i></a></li>
    {% endif %}  
</ul>