config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SerchView.as_view(), name="search"),
]

templates/mixins/room_card.html
<div class="flex items-center w-full">
    <div class="mr-5">
        <a href="{% url 'rooms:detail' room.pk %}">
            <img class="w-48 border rounded-lg border-pink-600" src="{{room.first_photo}}" />
        </a>
    </div>
    <div>
        <div class="flex">
            <div class="mr-1">
                <h3 class="font-semibold text-lg">Title:</h3>
            </div>
            <div class="text-lg">
                <a href="{% url 'rooms:detail' room.pk %}">{{room.title}}</a>
            </div>
        </div>
        <div class="flex mt-3">
            <div class="mr-1">
                <h3 class="font-semibold text-lg" >Creater:</h3>
            </div>
            <div class="text-lg">
                <a>{{room.creater}}</a>
            </div>
        </div>
        <div class="flex mt-3">
            <div class="mr-1">
                <h3 class="font-semibold text-lg">Tags:</h3>
            </div>
            <div class="text-lg grid grid-cols-8">
                {% for tag in room.tag.all %}
                    <a class="bg-pink-100 p-1 rounded-lg m-1 border border-pink-600 text-center">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>