config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SerchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=50)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Tag(AbstractItem):

    """ Tags Model Definition """

    class Meta:
        ordering = ("name",)


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=50)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    title = models.CharField(max_length=200)
    creater = models.CharField(max_length=50)
    tag = models.ManyToManyField(Tag, related_name="rooms", blank=True)
    upload_user = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE, default=""
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_all_photos(self):
        photos = self.photos.all()
        return photos

rooms/forms.py
from django import forms
from . import models


class SearchForm(forms.Form):

    title = forms.CharField(required=False)
    creater = forms.CharField(required=False)
    tags = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):

    file = forms.FileField(widget=forms.ClearableFileInput(attrs={"multiple": True}))

    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = ("title", "creater", "tag")

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
import os
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse, redirect
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 5
    paginate_orphans = 2
    context_object_name = "rooms"
    ordering = ("-created",)


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SerchView(View):
    def get(self, request):
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            creater = form.cleaned_data.get("creater")
            tags = form.cleaned_data.get("tags")

            filter_args = {}

            if title is not None:
                filter_args["title__icontains"] = title

            if creater is not None:
                filter_args["creater__icontains"] = creater

            for tag in tags:
                filter_args["tag"] = tag

            rooms = models.Room.objects.filter(**filter_args)
            rooms = reversed(rooms)

            # To do
            # paginiate 제한, page nav 만들기

        return render(
            request,
            "rooms/search.html",
            {"form": form, "rooms": rooms},
        )


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    fields = (
        "title",
        "creater",
        "tag",
    )
    template_name = "rooms/room_edit.html"

    def get_success_url(self):
        upload_user_pk = self.object.upload_user.pk
        return reverse("users:profile", args=[upload_user_pk])

    def get_object(self, quryset=None):
        room = super().get_object(queryset=quryset)
        if room.upload_user.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, quryset=None):
        room = super().get_object(queryset=quryset)
        if room.upload_user.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.upload_user.pk != user.pk:
            messages.error(request, "이미지를 지울 수 없습니다")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    model = models.Photo
    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        # form.save_m2m() 다중 업로드 구현하기
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.upload_user = self.request.user
        room.save()
        form.save_m2m()
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/home.html
{% extends "base.html" %} 

{% block page_name %}
    Home
{% endblock page_name %}

{% block main_page %}

    {% include "partials/header.html" %}

    {% for room in lastset_rooms %}
        <h1>{{room}}</h1>
    {% endfor %} 

    <h5>
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">이전 페이지</a>
        {% endif %}
            
        {% for page in page.paginator.page_range %}
            <a href="?page={{page}}">{{page}}</a>
        {% endfor %}
        
        {% if page.has_next  %}
            <a href="?page={{page.next_page_number}}">다음 페이지</a>
        {% endif %}
    </h5>

    

    {% include "partials/footer.html" %}

{% endblock main_page %}

templates/rooms/photo_create.html
{% extends "base.html" %} 

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        {{photos}}
        <!-- <p>
            <label for="id_title">이름: </label>
            {{form.caption}}
        </p>
        <p>
            <label for="id_title">파일: </label>
            {{form.file}}
        </p> -->
        <p class="flex justify-center">
            <button class="btn">수정</button>
        </p>

    </form>

{% endblock main_page %}

templates/rooms/photo_edit.html
{% extends "base.html" %} 

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST"">
        {% csrf_token %}

        <p>
            <label for="id_title">이름: </label>
            {{form.caption}}
              
        </p>
       
        <p class="flex justify-center">
            <button class="btn">수정</button>
        </p>

    </form>

{% endblock main_page %}

templates/rooms/room_card.html
<div class="mr-5">
    <a href="{% url 'rooms:detail' room.pk %}">
        <img class="w-48 border rounded-lg border-pink-600" src="{{room.first_photo}}" />
    </a>
</div>
<div>
    <div class="flex">
        <div class="mr-1">
            <h3 class="font-semibold text-lg">Title:</h3>
        </div>
        <div class="text-lg">
            <a href="{% url 'rooms:detail' room.pk %}">{{room.title}}</a>
        </div>
    </div>
    <div class="flex mt-3">
        <div class="mr-1">
            <h3 class="font-semibold text-lg" >Creater:</h3>
        </div>
        <div class="text-lg">
            <a>{{room.creater}}</a>
        </div>
    </div>
    <div class="flex mt-3">
        <div class="mr-1">
            <h3 class="font-semibold text-lg">Tags:</h3>
        </div>
        <div class="text-lg">
            {% for tag in room.tag.all %}
                <a>{{tag}}</a>
            {% endfor %}
        </div>
    </div>
</div>

templates/rooms/room_create.html
{% extends "base.html" %} 

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST"">
        {% csrf_token %}
        <p>
            <label for="id_title">Title: </label>
            {{form.title}}
            {% if form.title.errors %}
                {% for error in form.title.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p>
            <label for="id_creater">Creater: </label>
            {{form.creater}}
            {% if form.creater.errors %}
                {% for error in form.creater.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p class="grid">
            <label class="mr-1" for="id_tag">Tags: </label>
            {{form.tag}}
            {% if form.tag.errors %}
                {% for error in form.tag.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}
            <span>Ctrl + Click</span>  
        </p>
        <p class="flex justify-center">
            <button class="btn">업로드</button>
        </p>
    </form>

{% endblock main_page %}

templates/rooms/room_detail.html
{% extends "base.html" %} 

{% block page_title %}
    {{room.title}}
{% endblock page_title %}

{% block main_page %}
    <div class="m-5 flex  justify-center bg-pink-50 rounded-md w-4/5 items-center">
        <div class="font-semibold text-xl">{{room.title}}</div>
    </div>

    <div class="flex flex-col items-center mb-20">
        {% for photo in room.get_all_photos %}
            <img src="{{photo.file.url}}" class="w-3/5 h-auto mb-2">
        {% endfor %}
    </div>
{% endblock main_page %}

templates/rooms/room_edit.html
{% extends "base.html" %} 

{% block page_title %}
    Room Edit
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST"">
        {% csrf_token %}
        <p>
            <label for="id_title">Title: </label>
            {{form.title}}
            {% if form.title.errors %}
                {% for error in form.title.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p>
            <label for="id_creater">Creater: </label>
            {{form.creater}}
            {% if form.creater.errors %}
                {% for error in form.creater.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p class="grid">
            <label class="mr-1" for="id_tag">Tags: </label>
            {{form.tag}}
            {% if form.tag.errors %}
                {% for error in form.tag.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}
            <span>Ctrl + Click</span>  
        </p>
        <p class="flex justify-center">
            <button class="btn">수정</button>
        </p>
        <div class="flex justify-center font-normal text-sm text-pink-900">
            <a href="{% url 'rooms:photos' room.pk %}">이미지 수정</a>
        </div>
    </form>

{% endblock main_page %}

templates/rooms/room_list.html
{% extends "base.html" %} 

{% block page_title %}
    Home
{% endblock page_title %}

{% block main_page %}
    
    {% for room in rooms %}
        <div class="room_list_base">
            {% include "mixins/room_card.html" with room=room %}
        </div>
    {% endfor %} 
    
    <div class="my-5 font-semibold justify-center">
        <!-- 이전 버튼-->
        {% if page_obj.has_previous %}
            <a class="nav" href="?page={{page_obj.previous_page_number}}">
                <i class="fas fa-angle-left fa-lg"></i>
            </a>
        {% endif %}

        <!-- 현재 페이지 -->
        {% for page in page_obj.paginator.page_range %}
            {% if page == page_obj.number %}
                <a class="nav font-extrabold" href="?page={{page}}">{{page}}</a>
            {% else %}
                <a class="nav" href="?page={{page}}">{{page}}</a>
                {% endif %}
            {% endfor %}
        
        <!-- 다음 버튼 -->
        {% if page_obj.has_next  %}
            <a class="nav" href="?page={{page_obj.next_page_number}}">
                <i class="fas fa-angle-right fa-lg"></i>
            </a>
        {% endif %}
    </div>

{% endblock main_page %}

templates/rooms/room_photos.html
{% extends "base.html" %} 

{% block page_title %}
    {{room.title}} Photos
{% endblock page_title %}

{% block main_page %}

<div class="container mx-auto my-10 flex flex-col ">
    <a href="{% url 'rooms:edit' room.pk %}"><i class="fas fa-chevron-left fa-lg ml-3"></i></a>
    <div class="ml-3 mt-3 mb-5">
        <a href="{% url 'rooms:add_photos' room.pk %}" class="btn">이미지 추가</a>
    </div>
    {% for photo in room.photos.all %}
    <div class="m-3 p-5 flex justify-between border border-pink-500 border-opacity-30">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-40">
            <span class="ml-5 text-xl font-semibold">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col justify-center w-1/5">
            <a href="{% url 'rooms:edit_photo' room.pk photo.pk %}" class="btn text-center font-bold">이름 수정</a>
            <a href="{% url 'rooms:delete_photo' room.pk photo.pk %}" class="text-center font-bold bg-red-600 py-2 px-9 my-3 rounded-md text-white">삭제</a> 
        </div>
        
    </div>
    {% endfor %}
</div>

{% endblock main_page %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block main_page %}

    <form class="search border-b pb-7 border-pink-500 border-opacity-10" action="{% url 'rooms:search' %}" method="GET">
        {{form.as_p}}
        <div class="flex justify-end">
            <button class="btn">검색</button>
        </div>
    </form>
        
    {% for room in rooms %}
        <div class="room_list_base">
            {% include "mixins/room_card.html" with room=room %}
        </div>
    {% endfor %}

    
    

  
{% endblock main_page %}