config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add_photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path("search/", views.SerchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse


class User(AbstractUser):

    """ CustomUserModel """

    avatar = models.ImageField(upload_to="avatars", blank=True)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 틀렸습니다"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("없는 계정입니다"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "email")

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Password 확인")

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(DetailView):

    model = models.User


class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView):

    model = models.User
    template_name = "users/update_profile.html"
    fields = ("first_name",)

    def get_object(self, qureyset=None):
        return self.request.user


class UpdatePasswordView(mixins.LoggedInOnlyView, PasswordChangeView):

    template_name = "users/update_password.html"
    success_url = reverse_lazy("core:home")

templates/users/login.html
{% extends "base.html" %} 

{% block page_title %}
    Log In
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_email">Email</label>
            {{form.email}}
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p>
            <label for="id_password">password</label>
            {{form.password}}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <div class="flex justify-center">
            <button class="btn">로그인</button>
        </div>
    </form>

{% endblock main_page %}

templates/users/signup.html
{% extends "base.html" %} 

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST" action="{% url 'users:signup' %}">
        {% csrf_token %}
        <p>
            <label for="id_password1">닉네임</label>
            {{form.first_name}}
            {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                    <span class="flex text-red-700 font-medium text-sm">{{error}}</span>
                {% endfor %}
            {% endif %} 
        </p>
        <p>
            <label for="id_email">Email</label>
            {{form.email}}
            
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <span class="flex text-red-700 font-medium text-sm">{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p>
            <label for="id_password">password</label>
            {{form.password}}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span class="flex text-red-700 font-medium text-sm">{{error}}</span>
                {% endfor %}
            {% endif %}
        </p>
        <p>
            <label for="id_password1">password 확인</label>
            {{form.password1}}
            {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                    <span class="flex text-red-700 font-medium text-sm">{{error}}</span>
                {% endfor %}
            {% endif %} 
        </p>
        <div class="flex justify-end">
            <button class="btn">회원가입</button>
        </div>
    </form>

{% endblock main_page %}

templates/users/update_password.html
{% extends "base.html" %} 

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST"">
        {% csrf_token %}
        <p>
            <label for="id_old_password">지금 사용 중인 비밀번호: </label>
            {{form.old_password}}
            {% if form.old_password.errors %}
                {% for error in form.old_password.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p>
            <label for="id_new_password1">새로운 비밀번호: </label>
            {{form.new_password1}}
            {% if form.new_password1.errors %}
                {% for error in form.new_password1.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}
            <ul class="text-red-600 text-sm">
                <li>비밀번호는 다른 개인 정보와 비슷할 수 없습니다.</li>
                <li>비밀번호는 8 자 이상 이어야 합니다.</li>
                <li>비밀번호는 흔하거나 단순한 비밀번호는 사용할 수 없습니다.</li>
                <li>비밀번호는 숫자만으로 구성할 수 없습니다.</li>
            </ul>
        </p>
        <p>
            <label for="id_new_password2">새로운 비밀번호 확인: </label>
            {{form.new_password2}}
            {% if form.new_password2.errors %}
                {% for error in form.new_password2.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p class="flex justify-center">
            <button class="btn">수정</button>
        </p>
    </form>

{% endblock main_page %}

templates/users/update_profile.html
{% extends "base.html" %} 

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block main_page %}

    <form class="login" method="POST"">
        {% csrf_token %}
        <p>
            <label for="id_first_name">닉네임: </label>
            {{form.first_name}}
            {% if form.first_name.errors %}
                {% for error in form.first_name.error %}
                  <span>{{error}}</span>
                {% endfor %}
            {% endif %}  
        </p>
        <p class="flex justify-center">
            <button class="btn">수정</button>
        </p>
    </form>

{% endblock main_page %}

templates/users/user_detail.html
{% extends "base.html" %} 

{% block page_title %}
    Profile
{% endblock page_title %}

{% block main_page %}

    <div class="flex flex-col items-center my-10 p-5 border rounded-2xl border-pink-600 bg-pink-100">
        <p class="mb-5">
            <span class="font-bold text-2xl" >{{user.first_name}}</span>
        </p>
        <p>
            <a href="{% url 'users:update' %}" class="btn">닉네임 수정</a>
            <a href="{% url 'users:password' %}" class="btn">비밀번호 수정</a> 

        </p>
    </div>

    
    {% if user.rooms.all.count > 0 %}
        <div class="w-full flex flex-col items-center border-t-2 pt-8  border-pink-500 border-opacity-5">
            <h3 class="bg-pink-100 py-1 px-3 rounded-lg border border-pink-600 font-medium text-xl">업로드한 만화</h3>
            {% for room in user.rooms.all %}
                <div class="room_list_base flex flex-col">
                    {% include "mixins/room_card.html" with room=room %}
                    <div class="flex w-full justify-around items-center mt-3">
                        <div></div>
                        <a href="{% url 'rooms:edit' room.pk %}" class="btn">수정</a>
                    </div>
                </div>
            {% endfor %} 
        </div>
    {% endif %}
        
{% endblock main_page %}